### ISSUE TITLE
[bug] fc in 2.1 from gplay crash reports

### ISSUE THREAD

**Issue by asksven** [asksven/BetterBatteryStats#736]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at com.asksven.betterbatterystats.data.GraphSerie.<init>(GraphSerie.java:38)
	at com.asksven.betterbatterystats.adapters.GraphsAdapter.seriesSetup(GraphsAdapter.java:111)
	at com.asksven.betterbatterystats.adapters.GraphsAdapter.setSeries(GraphsAdapter.java:62)
	at com.asksven.betterbatterystats.NewGraphActivity$LoadSerieData.onPostExecute(NewGraphActivity.java:207)
	at com.asksven.betterbatterystats.NewGraphActivity$LoadSerieData.onPostExecute(NewGraphActivity.java:1)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)

**Comment by asksven** [comment]
already fixed in 2.1
