### ISSUE TITLE
[bug] app crashes when starting

### ISSUE THREAD

**Issue by capshort** [asksven/BetterBatteryStats#860]
I'm suffering from a non-reproducible bug that crashes the app immediately when I start it. When it crashes once, it also crashes reliably on every subsequent start until I clean the app data manually. Then, usually after one to two weeks of use, this happens again.

Might be that you can in some way defer from the logcat what has happened:

```
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: FATAL EXCEPTION: main
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: Process: com.asksven.betterbatterystats, PID: 31997
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/asksven/android/common/privateapiproxies/R$layout;
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at com.asksven.android.common.AppRater.showRateDialog(AppRater.java:84)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at com.asksven.android.common.AppRater.app_launched(AppRater.java:72)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at com.asksven.betterbatterystats.StatsActivity.onCreate(StatsActivity.java:255)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7009)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7000)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.asksven.android.common.privateapiproxies.R$layout" on path: DexPathList[[zip file "/data/app/com.asksven.betterbatterystats-w_GeRfCzYDe-nduT3mh-qA==/base.apk"],nativeLibraryDirectories=[/data/app/com.asksven.betterbatterystats-w_GeRfCzYDe-nduT3mh-qA==/lib/arm, /system/lib, /system/vendor/lib]]
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-05 13:18:43.691 u0_a3 31997 31997 E AndroidRuntime: 	... 16 more
02-05 13:18:43.694  1000   819  4998 W ActivityManager:   Force finishing activity com.asksven.betterbatterystats/.StatsActivity
02-05 13:18:43.704  1000   819  1259 I ActivityManager: Showing crash dialog for package com.asksven.betterbatterystats u0
```

**Comment by asksven** [comment]
Fixed since AppRater was removed
