### ISSUE TITLE
[bug] Unable to instantiate service com.asksven.betterbatterystats.services.AppWidgetJobService

### ISSUE THREAD

**Issue by WangGuox1n** [asksven/BetterBatteryStats#866]
Hi, 
I'm using master project,  when testing the app, there is an exception:
**STACK_TRACE**= E/AndroidRuntime( 6326): FATAL EXCEPTION: main
E/AndroidRuntime( 6326): Process: com.asksven.betterbatterystats, PID: 6326
E/AndroidRuntime( 6326): java.lang.RuntimeException: Unable to instantiate service com.asksven.betterbatterystats.services.AppWidgetJobService: java.lang.ClassNotFoundException: Didn't find class "com.asksven.betterbatterystats.services.AppWidgetJobService" on path: DexPathList[[zip file "/data/app/com.asksven.betterbatterystats-1.apk", zip file "/data/app/com.asksven.betterbatterystats-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.asksven.betterbatterystats-1, /data/app-lib/com.asksven.betterbatterystats-1, /system/lib]]
E/AndroidRuntime( 6326): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2543)
E/AndroidRuntime( 6326): 	at android.app.ActivityThread.access$1800(ActivityThread.java:135)
E/AndroidRuntime( 6326): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
E/AndroidRuntime( 6326): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 6326): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 6326): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 6326): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6326): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 6326): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 6326): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 6326): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 6326): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.asksven.betterbatterystats.services.AppWidgetJobService" on path: DexPathList[[zip file "/data/app/com.asksven.betterbatterystats-1.apk", zip file "/data/app/com.asksven.betterbatterystats-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.asksven.betterbatterystats-1, /data/app-lib/com.asksven.betterbatterystats-1, /system/lib]]
E/AndroidRuntime( 6326): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 6326): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime( 6326): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime( 6326): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2540)
E/AndroidRuntime( 6326): 	... 10 more

is it a known issue? or a new bug of BetterBatteryStats

**Comment by WangGuox1n** [comment]
Second Exception:
**STACK_TRACE**=  E/AndroidRuntime(23126): FATAL EXCEPTION: main
E/AndroidRuntime(23126): Process: com.asksven.betterbatterystats, PID: 23126
E/AndroidRuntime(23126): java.lang.NoClassDefFoundError: android.app.job.JobScheduler
E/AndroidRuntime(23126): 	at com.asksven.betterbatterystats.handlers.OnBootHandler.deletePendingAppWidgetsJobs(OnBootHandler.java:157)
E/AndroidRuntime(23126): 	at com.asksven.betterbatterystats.handlers.OnBootHandler.scheduleAppWidgetsJobImmediate(OnBootHandler.java:115)
E/AndroidRuntime(23126): 	at com.asksven.betterbatterystats.PreferencesFragmentActivity$PrefsFragment.onSharedPreferenceChanged(PreferencesFragmentActivity.java:204)
E/AndroidRuntime(23126): 	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:475)
E/AndroidRuntime(23126): 	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:385)
E/AndroidRuntime(23126): 	at android.preference.Preference.tryCommit(Preference.java:1372)
E/AndroidRuntime(23126): 	at android.preference.Preference.persistBoolean(Preference.java:1638)
E/AndroidRuntime(23126): 	at android.preference.TwoStatePreference.setChecked(TwoStatePreference.java:84)
E/AndroidRuntime(23126): 	at android.preference.TwoStatePreference.onClick(TwoStatePreference.java:70)
E/AndroidRuntime(23126): 	at android.preference.Preference.performClick(Preference.java:952)
E/AndroidRuntime(23126): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
E/AndroidRuntime(23126): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime(23126): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
E/AndroidRuntime(23126): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
E/AndroidRuntime(23126): 	at android.widget.AbsListView$3.run(AbsListView.java:3645)
E/AndroidRuntime(23126): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(23126): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(23126): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(23126): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(23126): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(23126): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(23126): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(23126): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(23126): 	at dalvik.system.NativeStart.main(Native Method)
