### ISSUE TITLE
window leak in StatsActivity

### ISSUE THREAD

**Issue by anlalalu** [asksven/BetterBatteryStats#869]
###### Reproduction Steps

1. long click 'more options'
2. press 'back' quickly

###### Stack Trace

E/WindowManager: android.view.WindowLeaked: Activity com.asksven.betterbatterystats.StatsActivity has leaked window android.widget.LinearLayout{52978dcc V.E..... ......I. 0,0-264,96} that was originally added here
                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                    at android.support.v7.widget.TooltipPopup.show(TooltipPopup.java:86)
                                                    at android.support.v7.widget.TooltipCompatHandler.show(TooltipCompatHandler.java:174)
                                                    at android.support.v7.widget.TooltipCompatHandler.onLongClick(TooltipCompatHandler.java:123)
                                                    at android.view.View.performLongClick(View.java:4474)
                                                    at android.view.View$CheckForLongPress.run(View.java:18401)
                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:136)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                    at dalvik.system.NativeStart.main(Native Method)

###### Debug info
App Version = 2.5

Android Version = 4.4.4

**Comment by anlalalu** [comment]
Do you consider this as a defect? If so, please let me know, thank you.
