### ISSUE TITLE
crash when rotate screen in Settings

### ISSUE THREAD

**Issue by anlalalu** [asksven/BetterBatteryStats#870]
###### Reproduction Steps

1. tap 'more options'
2. tap 'Settings'
3. rotate the screen

###### Stack Trace

E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.asksven.betterbatterystats, PID: 6604
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.asksven.betterbatterystats/com.asksven.betterbatterystats.PreferencesFragmentActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class fragment
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3724)
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class fragment
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                     at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                     at com.asksven.betterbatterystats.PreferencesFragmentActivity.onCreate(PreferencesFragmentActivity.java:55)
                                                     at android.app.Activity.performCreate(Activity.java:5231)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3724) 
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.IllegalStateException: Fragment com.asksven.betterbatterystats.PreferencesFragmentActivity$PrefsFragment did not create a view.
                                                     at android.app.Activity.onCreateView(Activity.java:4809)
                                                     at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:389)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:689)

###### Debug info
App Version = 2.5

Android Version = 4.4.4

**Comment by anlalalu** [comment]
Do you consider this as a defect? If so, please let me know, thank you.
