### ISSUE TITLE
crash when setting preferences

### ISSUE THREAD

**Issue by anlalalu** [asksven/BetterBatteryStats#871]
###### Reproduction Steps

1. tap 'more options'
2. tap 'Settings'
3. scroll down
4. tap 'Show only%'

###### Stack Trace

E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.asksven.betterbatterystats, PID: 7327
                                                 java.lang.NoClassDefFoundError: android.app.job.JobScheduler
                                                     at com.asksven.betterbatterystats.handlers.OnBootHandler.deletePendingAppWidgetsJobs(OnBootHandler.java:157)
                                                     at com.asksven.betterbatterystats.handlers.OnBootHandler.scheduleAppWidgetsJobImmediate(OnBootHandler.java:115)
                                                     at com.asksven.betterbatterystats.PreferencesFragmentActivity$PrefsFragment.onSharedPreferenceChanged(PreferencesFragmentActivity.java:204)
                                                     at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:475)
                                                     at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:385)
                                                     at android.preference.Preference.tryCommit(Preference.java:1372)
                                                     at android.preference.Preference.persistBoolean(Preference.java:1638)
                                                     at android.preference.TwoStatePreference.setChecked(TwoStatePreference.java:84)
                                                     at android.preference.TwoStatePreference.onClick(TwoStatePreference.java:70)
                                                     at android.preference.Preference.performClick(Preference.java:952)
                                                     at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
                                                     at android.widget.AdapterView.performItemClick(AdapterView.java:299)
                                                     at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
                                                     at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
                                                     at android.widget.AbsListView$3.run(AbsListView.java:3645)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

###### Screen Shot
![Screen Shot](https://user-images.githubusercontent.com/46981872/71352853-59d8ac80-25b2-11ea-8325-f18109e2a0c9.png)

###### Debug info
App Version = 2.5

Android Version = 4.4.4

**Comment by anlalalu** [comment]
Do you consider this as a defect? If so, please let me know, thank you.

**Comment by asksven** [comment]
Can not reproduce on current builds
