### ISSUE TITLE
Find a crash!

### ISSUE THREAD

**Issue by LvZW1895** [asksven/BetterBatteryStats#877]
Hello, this crash happened by accident when I was testing. I hope it can help you to debug.

APK Version :2.5
AndroidOS Version = 9.0

CRASH: com.asksven.betterbatterystats_xdaedition (pid 30194) (dump time: 2021-03-15 11:36:24
Version: 2.5
Long Msg: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:537)
	at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:526)
	at com.asksven.betterbatterystats.PreferencesFragmentActivity$PrefsFragment.onSharedPreferenceChanged(PreferencesFragmentActivity.java:188)
	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:607)
	at android.app.SharedPreferencesImpl$EditorImpl.commit(SharedPreferencesImpl.java:593)
	at com.asksven.android.common.utils.SharedPreferencesUtils.loadSharedPreferencesFromFile(SharedPreferencesUtils.java:149)
	at com.asksven.betterbatterystats.ImportExportPreferencesActivity$2.onClick(ImportExportPreferencesActivity.java:81)
	at android.view.View.performClick(View.java:6663)
	at android.view.View.performClickInternal(View.java:6635)
	at android.view.View.access$3100(View.java:794)
	at android.view.View$PerformClick.run(View.java:26199)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7593)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by asksven** [comment]
can not reproduce
