### ISSUE TITLE
the app throws com.asksven.android.common.privateapiproxies.BatteryInfoUnavailableException when click "Raw Stats"

### ISSUE THREAD

**Issue by androidAppGuard** [asksven/BetterBatteryStats#888]
**the environment is as follows:**
```
App version: master
Android version: 6.0
Device: Nexux_5X
```
**The steps to reproduce:**
![11_betterbatterystats_BatteryInfoUnavailableException.gif](https://s2.loli.net/2022/05/12/yjmbAHD8tUsRqch.gif)
**The exception log is as follows:**
```
05-12 13:45:55.219 5397-5505/com.asksven.betterbatterystats_xdaedition E/StatsProvider: Exception: com.asksven.android.common.privateapiproxies.BatteryInfoUnavailableException
        at com.asksven.android.common.privateapiproxies.BatteryStatsProxy.getBatteryRealtime(BatteryStatsProxy.java:643)
        at com.asksven.betterbatterystats.data.StatsProvider.getCurrentOtherUsageStatList(StatsProvider.java:1809)
        at com.asksven.betterbatterystats.RawStatsActivity$LoadStatData.doInBackground(RawStatsActivity.java:205)
        at com.asksven.betterbatterystats.RawStatsActivity$LoadStatData.doInBackground(RawStatsActivity.java:188)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
05-12 13:45:55.219 5397-5505/com.asksven.betterbatterystats_xdaedition E/RawStatsActivity: Exception: com.asksven.android.common.privateapiproxies.BatteryInfoUnavailableException
        at com.asksven.android.common.privateapiproxies.BatteryStatsProxy.computeBatteryRealtime(BatteryStatsProxy.java:600)
        at com.asksven.betterbatterystats.data.StatsProvider.getCurrentOtherUsageStatList(StatsProvider.java:1827)
        at com.asksven.betterbatterystats.RawStatsActivity$LoadStatData.doInBackground(RawStatsActivity.java:205)
        at com.asksven.betterbatterystats.RawStatsActivity$LoadStatData.doInBackground(RawStatsActivity.java:188)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by asksven** [comment]
As long as BATTERY_STATS is not available (red markers in the permissions) there no way BBS will work
