### ISSUE TITLE
BBS crash when use shelter app and work space

### ISSUE THREAD

**Issue by mydreamworldpolly** [asksven/BetterBatteryStats#904]
when open "partial wakelock",bbs crash.Probable reason is multiuser. When BBS detects some apps installed in android work space, it crash.

additional info:
https://paste.evolution-x.org/lcq2Cp

time: 1662271076617
msg: java.lang.SecurityException: getPackagesForUid: UID 10005 requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS or android.permission.INTERACT_ACROSS_PROFILES to access user .
stacktrace: java.lang.SecurityException: getPackagesForUid: UID 10005 requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS or android.permission.INTERACT_ACROSS_PROFILES to access user .
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackagesForUid(IPackageManager.java:5389)
	at android.app.ApplicationPackageManager$3.recompute(ApplicationPackageManager.java:1050)
	at android.app.ApplicationPackageManager$3.recompute(ApplicationPackageManager.java:1044)
	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:562)
	at android.app.ApplicationPackageManager.getPackagesForUid(ApplicationPackageManager.java:1063)
	at com.asksven.android.common.nameutils.UidNameResolver.getNameForUid(UidNameResolver.java:107)
	at com.asksven.android.common.privateapiproxies.StatElement.getFullQualifiedName(StatElement.java:88)
	at com.asksven.android.common.privateapiproxies.StatElement.getFqn(StatElement.java:112)
	at com.asksven.betterbatterystats.adapters.StatsAdapter.getView(StatsAdapter.java:231)
	at android.widget.AbsListView.obtainView(AbsListView.java:2400)
	at android.widget.ListView.makeAndAddView(ListView.java:2067)
	at android.widget.ListView.fillDown(ListView.java:793)
	at android.widget.ListView.fillFromTop(ListView.java:855)
	at android.widget.ListView.layoutChildren(ListView.java:1838)
	at android.widget.AbsListView.onLayout(AbsListView.java:2197)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6411)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6411)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6411)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6411)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6411)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6411)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6411)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:797)
	at android.view.View.layout(View.java:23203)
	at android.view.ViewGroup.layout(ViewGroup.java:6411)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3753)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3203)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2177)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8803)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[Main Website](https://evolution-x.org/) [Wiki](https://wiki.evolution-x.org/)

**Comment by Iey4iej3** [comment]
same as https://github.com/asksven/BetterBatteryStats/issues/902

**Comment by SedyBenoitPeace** [comment]
I'm suffering with the same issue but I have just stock multiuser and no external apps, strange thing is if I uninstall and then reinstall and then I provide authorizations for a while it works, then it suddenly stops.

I read somewhere on XDA Thread that was possible to add the authorization for this with ADB, but looks like is not possible on my phone! I get "can't grant permission for this package" error or something like that on console.

Is there something I can do to help?
