### ISSUE TITLE
Not working on Pixel 8 Pro with Android 14

### ISSUE THREAD

**Issue by joserosapt** [asksven/BetterBatteryStats#921]
Here's the error message:

Build.VERSION.RELEASE: 14
Build.BRAND: google
Build.DEVICE: husky
Build.MANUFACTURERGoogle
Build.MODEL: Pixel 8 Pro
Build.VERSION.SDK_INT: 34

FAILURE: an unhandled exception occured

STACK TRACE
java.lang.ClassNotFoundException: Didn't find class "com.android.internal.os.BatteryStatsImpl" on path: DexPathList[[zip file "/data/app/~~BO3s176ysocDk986t0GHmA==/com.asksven.betterbatterystats-yiTzHj6_zPisIYmwkdPdwg==/base.apk"],nativeLibraryDirectories=[/data/app/~~BO3s176ysocDk986t0GHmA==/com.asksven.betterbatterystats-yiTzHj6_zPisIYmwkdPdwg==/lib/arm64, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.asksven.betterbatterystats.DiagnosticsActivity.diagGetService(DiagnosticsActivity.java:121)
	at com.asksven.betterbatterystats.DiagnosticsActivity.onResume(DiagnosticsActivity.java:95)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
	at android.app.Activity.performResume(Activity.java:8743)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4952)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4995)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by jason-eu** [comment]
https://github.com/asksven/BetterBatteryStats/issues/915
