### ISSUE TITLE
Diagnostics shows error: BBS not tracking data

### ISSUE THREAD

**Issue by Bharatyadav15** [asksven/BetterBatteryStats#929]
![Screenshot_20240407_124303](https://github.com/asksven/BetterBatteryStats/assets/99937136/d5b48020-cc5b-4cbc-a61b-8e5ed4e03340)
Using Samsung s23 oneui 6.1 and bbs not showing any data except alarms and CPU starts. Found app showing error in diagnostics for which I've attached screenshots.

**Comment by ApolloGods** [comment]
same to me


Build.VERSION.RELEASE: 14
Build.BRAND: samsung
Build.DEVICE: b0s
Build.MANUFACTURERsamsung
Build.MODEL: SM-S908B
Build.VERSION.SDK_INT: 34

FAILURE: an unhandled exception occured

STACK TRACE
java.lang.ClassNotFoundException: Didn't find class "com.android.internal.os.BatteryStatsImpl" on path: DexPathList[[zip file "/data/app/~~LiNMfZclfS4sacmJMrloSg==/com.asksven.betterbatterystats--iI6l7jRB8MUeDeN_m6uxw==/base.apk"],nativeLibraryDirectories=[/data/app/~~LiNMfZclfS4sacmJMrloSg==/com.asksven.betterbatterystats--iI6l7jRB8MUeDeN_m6uxw==/lib/arm64, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.asksven.betterbatterystats.DiagnosticsActivity.diagGetService(DiagnosticsActivity.java:121)
	at com.asksven.betterbatterystats.DiagnosticsActivity.onResume(DiagnosticsActivity.java:95)
	at android.app.Instrumentation.callActivityOnResume(Unknown Source:3)
	at android.app.Activity.performResume(Unknown Source:64)
	at android.app.ActivityThread.performResumeActivity(Unknown Source:92)
	at android.app.ActivityThread.handleResumeActivity(Unknown Source:15)
	at android.app.servertransaction.ResumeActivityItem.execute(Unknown Source:16)
	at android.app.servertransaction.ActivityTransactionItem.execute(Unknown Source:4)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(Unknown Source:32)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:79)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:221)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:185)
	at android.os.Looper.loop(Unknown Source:83)
	at android.app.ActivityThread.main(Unknown Source:107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:334)

S22 Ultra rooted OneUi 6.1

**Comment by sempasha** [comment]
Android 14 is not supported for now. See comment at issue [#912](https://github.com/asksven/BetterBatteryStats/issues/912#issuecomment-1987248937). This issue have to be closed as duplicate of #921, #915, #913 and #912
